// ==UserScript==
// @name         William responde ai
// @namespace    Squ3le0n script ?
// @version      0.1
// @description  teste liberação
// @author       william brayon
// @match        https://gist.github.com/Squ3let0n/ea2779cec517f3c126d34c8b374b409d
// @icon         https://www.google.com/s2/favicons?domain=github.com
// @grant        none
// ==/UserScript==

(function() {
    'use strict';

 
  const tela_de_blur = () => {
    document.querySelectorAll('login-disclaimer').forEach((disclaimer) => {
      disclaimer.parentNode.removeChild(disclaimer);
    });
    document.querySelectorAll('overlay-disclaimer').forEach((disclaimer) => {
      disclaimer.parentNode.removeChild(disclaimer);
    });
    document.querySelectorAll('.blur').forEach((element) => {
      element.classList.remove('blur');
    });
    document.querySelectorAll('.expand-btn').forEach((element) => {
      if (element.innerHTML === 'MOSTRAR SOLUÇÃO COMPLETA') {
        element.parentNode.removeChild(element);        
      }
    });
    document.querySelectorAll('.ReactModalPortal').forEach((disclaimer) => {
      disclaimer.parentNode.removeChild(disclaimer);
      document.body.classList.remove('ReactModal__Body--open');
    });
    const loginAlertTexts = Array.from(document.querySelectorAll('h2')).filter(el => el.innerText.includes('Loga aí pra continuar'));
    loginAlertTexts.forEach(loginAlert => {
      const parentEl = loginAlert.parentNode;
      parentEl.parentNode.removeChild(parentEl);        
    });
    
    const exerciseContainer = document.querySelector('div[class^="BookEditionPage__Container"]');
    if (exerciseContainer) observerPaywall.observe(exerciseContainer, observerPaywallConfig);
  }
  window.tela_de_blur = tela_de_blur;

  const observerStyle = new MutationObserver(function(mutations) {
    mutations.forEach(function(mutation) {
      mutation.target.removeAttribute("style");
    });
  });
  
  const observerPaywall = new MutationObserver(function(mutations) {
    mutations.forEach(function(mutation) {
      tela_de_blur();
    });
  });

  const observerStyleConfig = {
    attributes: true,
    attributeOldValue: true,
  }
  
  const observerPaywallConfig = {
    ...observerStyleConfig,
    childList: true,
  }
  
  const overlay = document.querySelector('.login-overlay');
  const main_wrapper = document.querySelector('.main-wrapper') || document.querySelector('.main-container');
  const btn = document.querySelector('#exercise-expand-button');
  
  const style = document.createElement('style');
  style.innerHTML =
    '.content-card * {' +
      'user-select: auto !important;' +
    '}' +
    '.blur {' + 
      '-webkit-filter: none !important;' +
      'filter: none !important;' +
      'pointer-events: all;' + 
    '}';
  document.querySelector('head').appendChild(style);
  
  if (overlay) observerStyle.observe(overlay, observerStyleConfig);
  if (main_wrapper) observerStyle.observe(main_wrapper, observerStyleConfig);
  observerPaywall.observe(document.body, observerStyleConfig);

  window.onload = () => {
    tela_de_blur();
  }
  
  btn && btn.parentNode.removeChild(btn);
  overlay && overlay.parentNode.removeChild(overlay);
})();
